import os

DATABASE_URL = os.getenv("SANSKRIT_DATABASE")

SECRET_KEY = os.getenv("SECRET_KEY")

SANSKRIT_EMAIL = os.getenv("SANSKRIT_EMAIL")
SANSKRIT_PASSWORD = os.getenv("SANSKRIT_PASSWORD")

ADMINISTRATOR_EMAIL = os.getenv("ADMINISTRATOR_EMAIL")